version: "3.9"
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:3000"
  customer-service:
    build: ./customer-services
    ports:
      - "8081:3000"
  order-service:
    build: ./order-services
    ports:
      - "8082:3000"
  inventory-service:
    build: ./inventory-services
    ports:
      - "8083:3000"
  payment-service:
    build: ./payment-services
    ports:
      - "8084:3000"
  menu-service:
    build: ./menu-services
    ports:
      - "8085:3000"

      